server:
  port: ${SERVER_PORT:8080}
spring:
  application.name: ${APPLICATION_NAME:spring-security-keycloak-resource}
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8484/auth/realms/REALM_TEST/protocol/openid-connect/token/introspect
          client-id: CLIENT_TEST
          client-secret: 9cbd1f8b-f3b4-458d-882c-d2dacfa49a6c

#        jwt:
#          jwk-set-uri: ${KEYCLOAK_REALM_CERT_URL:http://localhost:8484/auth/realms/REALM_TEST/protocol/openid-connect/certs}
#        jwt:
#          public-key-location: classpath:my-key.pub

#          token-uri: http://localhost:8484/auth/realms/REALM_TEST/protocol/openid-connect/token
#          user-info-uri: http://localhost:8484/auth/realms/REALM_TEST/protocol/openid-connect/userinfo
